spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  mvc:
    static-path-pattern: /pictures/**
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: file:pictures/
server:
  error:
    include-message: always
  port: 8081
jwt.secret: ${JWT_SECRET:tokendev}
google.clientId: ${GOOGLE_CI:765141960652-1056kh7b79p9omu0f87iocrhgn9vf0t7.apps.googleusercontent.com}
